inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'example/**/*'
    - 'spec/fixtures/**/*'
    - 'features/fixtures/**/*'

# We can't use ".freeze" on our constants in case users are monkey patching
# them — this would be a BC break
Style/MutableConstant:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

# These require newer version of Ruby than our minimum supported version, so
# have to be disabled
Style/HashTransformKeys: # Requires Ruby 2.5
  Enabled: false

Style/HashTransformValues: # Requires Ruby 2.4
  Enabled: false

Style/SlicingWithRange: # Requires Ruby 2.6
  Enabled: false
