sudo: false
language: ruby

before_install:
- gem update --system 2.6.14

install:
- bundle install --with "$GEMSETS" --binstubs

script:
- bundle exec ./bin/rake spec

jobs:
  include:
  - stage: test
    env: GEMSETS=test
    rvm: jruby-19mode
  - stage: test
    env: GEMSETS=test
    rvm: 1.9.3
  - stage: test
    env: GEMSETS=test
    rvm: 2.0.0
  - stage: test
    env: GEMSETS=test
    rvm: 2.1.10
  - stage: test
    env: GEMSETS="test sidekiq"
    rvm: 2.2.4
  - stage: test
    env: GEMSETS="test sidekiq coverage"
    rvm: 2.3.0
  - stage: test
    env: GEMSETS="test sidekiq"
    rvm: 2.4.1
  - stage: deploy
    env: GEMSETS="test doc"
    rvm: 2.4.1
    script: bundle exec rake rdoc
    if: tag =~ ^v[1-9]

deploy:
  provider: pages
  local_dir: rdoc # only include the contents of the generated docs dir
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # set in travis-ci dashboard
  on:
    tags: true # only deploy when tag is applied to commit
