sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
- 2.3.5
- 2.2.8
- 2.1.10
- 2.0.0
- 1.9.3
- jruby-19mode

before_install:
- gem install bundler -v 1.12
- gem update --system
- bundle --version
- gem --version
