sudo: false
language: ruby

before_install:
- gem install bundler -v 1.12
- gem update --system
- bundle --version
- gem --version

install:
- bundle _1.12.0_ install --with "$GEMSETS"

script:
- bundle _1.12.0_ exec rake

jobs:
  include:
  - stage: test
    env: GEMSETS=test
    rvm: jruby-19mode
  - stage: test
    env: GEMSETS=test
    rvm: 1.9.3
  - stage: test
    env: GEMSETS=test
    rvm: 2.0.0
  - stage: test
    env: GEMSETS=test
    rvm: 2.1.10
  - stage: test
    env: GEMSETS="test sidekiq"
    rvm: 2.2.4
  - stage: test
    env: GEMSETS="test sidekiq coverage"
    rvm: 2.3.0
