steps:
  - group: ":ruby: Basic tests"
    steps:
      - label: ':ruby: Ruby 1.9 unit tests'
        timeout_in_minutes: 30
        plugins:
          docker-compose#v3.1.0:
            run: ruby-unit-tests
            use-aliases: true
        env:
          RUBY_TEST_VERSION: "1.9.3"
          BUNDLE_VERSION: "1.12.0"

      - label: ':ruby: Ruby 2.7 unit tests'
        timeout_in_minutes: 30
        plugins:
          docker-compose#v3.1.0:
            run: ruby-unit-tests
            use-aliases: true
        env:
          RUBY_TEST_VERSION: "2.7"
          GEMSETS: "test sidekiq coverage"
      - label: ':ruby: Ruby 2.7 linting'
        timeout_in_minutes: 30
        plugins:
          docker-compose#v3.1.0:
            run: ruby-unit-tests
            use-aliases: true
        env:
          RUBY_TEST_VERSION: "2.7"
          GEMSETS: "test rubocop"
        command: "bundle exec ./bin/rubocop lib/"

      - label: ':ruby: Ruby 2.7 plain tests'
        timeout_in_minutes: 30
        plugins:
          docker-compose#v3.1.0:
            run: ruby-maze-runner
            use-aliases: true
            command: ["features/plain_features/", "--tags", "not @wip"]
        env:
          RUBY_TEST_VERSION: "2.7"

      - label: ':rails: Rails 6 Ruby 2.7 tests'
        timeout_in_minutes: 30
        plugins:
          docker-compose#v3.1.0:
            run: ruby-maze-runner
            use-aliases: true
            command: ["features/rails_features/",  "--tags", "@rails6 and not @wip"]
        env:
          RUBY_TEST_VERSION: "2.7"
          RAILS_VERSION: "6"

      - label: ':rails: Rails 7 Ruby 2.7 tests'
        timeout_in_minutes: 30
        plugins:
          docker-compose#v3.1.0:
            run: ruby-maze-runner
            use-aliases: true
            command: ["features/rails_features/",  "--tags", "@rails7 and not @wip"]
        env:
          RUBY_TEST_VERSION: "2.7"
          RAILS_VERSION: "7"
      - label: ':rails: Rails integrations Ruby 2.7 tests'
        timeout_in_minutes: 30
        plugins:
          docker-compose#v3.1.0:
            run: ruby-maze-runner
            use-aliases: true
            command: ["features/rails_features/", "--tags", "@rails_integrations"]
        env:
          RUBY_TEST_VERSION: "2.7"
          RAILS_VERSION: "_integrations"

      - label: ':construction: Delayed job tests'
        timeout_in_minutes: 30
        plugins:
          docker-compose#v3.1.0:
            run: ruby-maze-runner
            use-aliases: true
            command: ["features/delayed_job.feature", "--tags", "not @wip"]
        env:
          RUBY_TEST_VERSION: "2.5"

      - label: ':sidekiq: Sidekiq 6 tests'
        timeout_in_minutes: 30
        plugins:
          docker-compose#v3.1.0:
            run: ruby-maze-runner
            use-aliases: true
            command: ["features/sidekiq.feature", "--tags", "not @wip"]
        env:
          RUBY_TEST_VERSION: "2.5"
          SIDEKIQ_VERSION: "6"
