steps:
  - label: ':docker: Build CI image'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.1.0:
          build: ruby-maze-runner
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/ruby
          cache-from: ruby-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/ruby:base-ruby${BRANCH_NAME}
      - docker-compose#v3.1.0:
          push:
            - ruby-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/ruby:base-ruby${BRANCH_NAME}
            - ruby-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/ruby:base-ruby-latest

  - wait

  - label: ":ruby: Basic tests"
    commands:
      - buildkite-agent pipeline upload .buildkite/basic-tests-pipeline.yml

  - wait

  - label: ":ruby: Unit tests"
    commands:
      - buildkite-agent pipeline upload .buildkite/unit-tests-pipeline.yml

  - label: ":ruby: Plain tests"
    commands:
      - buildkite-agent pipeline upload .buildkite/plain-tests-pipeline.yml

  - label: ":rails: Rails tests"
    commands:
      - buildkite-agent pipeline upload .buildkite/rails-tests-pipeline.yml

  - label: ":hammer_and_wrench: Integrations tests"
    commands:
      - buildkite-agent pipeline upload .buildkite/integrations-tests-pipeline.yml

  - name: ':copyright: License Audit'
    plugins:
      docker-compose#v3.7.0:
        run: license_finder
    command: /bin/bash -lc '/scan/scripts/license_finder.sh'
