steps:
  - label: ':docker: Build CI image'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.1.0:
          build: ruby-maze-runner
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/ruby
          cache-from: ruby-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/ruby:base-ruby${BRANCH_NAME}
      - docker-compose#v3.1.0:
          push:
            - ruby-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/ruby:base-ruby${BRANCH_NAME}
            - ruby-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/ruby:base-ruby-latest

  - wait

  - label: ':ruby: Ruby 2.7 plain tests'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ["features/plain_features/", "--tags", "not @wip"]
    env:
      RUBY_TEST_VERSION: "2.7"

  - label: ':rails: Rails 6 Ruby 2.7 tests'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ["features/rails_features/",  "--tags", "@rails6 and not @wip"]
    env:
      RUBY_TEST_VERSION: "2.7"
      RAILS_VERSION: "6"

  - label: ':rails: Rails 7 Ruby 2.7 tests'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ["features/rails_features/",  "--tags", "@rails7 and not @wip"]
    env:
      RUBY_TEST_VERSION: "2.7"
      RAILS_VERSION: "7"
  - label: ':rails: Rails integrations Ruby 2.7 tests'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ["features/rails_features/", "--tags", "@rails_integrations"]
    env:
      RUBY_TEST_VERSION: "2.7"
      RAILS_VERSION: "_integrations"

  - label: ':construction: Delayed job tests'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ["features/delayed_job.feature", "--tags", "not @wip"]
    env:
      RUBY_TEST_VERSION: "2.5"

  - label: ':sidekiq: Sidekiq 6 tests'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ["features/sidekiq.feature", "--tags", "not @wip"]
    env:
      RUBY_TEST_VERSION: "2.5"
      SIDEKIQ_VERSION: "6"

  - wait

  - label: ':ruby: Ruby {{matrix}} plain tests'
    matrix:
      - "1.9.3"
      - "2.0"
      - "2.1"
      - "2.2"
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ["features/plain_features", "--tags", "not @wip"]
    env:
      RUBY_TEST_VERSION: "{{matrix}}"
      BUNDLE_VERSION: "1.12.0"
    concurrency: 8
    concurrency_group: 'ruby/slow-maze-runner-tests'

  - label: ':ruby: Ruby {{matrix}} plain tests'
    matrix:
      - '2.3'
      - '2.4'
      - '2.5'
      - '2.6'
      - '3.0'
      - '3.1'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ["features/plain_features/", "--tags", "not @wip"]
    env:
      RUBY_TEST_VERSION: "{{matrix}}"
    concurrency: 8
    concurrency_group: 'ruby/slow-maze-runner-tests'

  - label: ':sidekiq: Sidekiq {{matrix}} tests'
    matrix:
      - '2'
      - '3'
      - '4'
      - '5'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ["features/sidekiq.feature", "--tags", "not @wip"]
    env:
      RUBY_TEST_VERSION: "2.5"
      SIDEKIQ_VERSION: "{{matrix}}"
    concurrency: 4
    concurrency_group: 'ruby/integrations-maze-runner-tests'

  - label: ':rails: Rails 3 Ruby {{matrix}} tests'
    matrix:
      - '2.0'
      - '2.1'
      - '2.2'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ["features/rails_features/", "--tags", "@rails3 and not @wip"]
    env:
      RUBY_TEST_VERSION: "{{matrix}}"
      RAILS_VERSION: "3"
      BUNDLE_VERSION: "1.12.0"
    concurrency: 8
    concurrency_group: 'ruby/slow-maze-runner-tests'

  - label: ':rails: Rails 3 Ruby {{matrix}} tests'
    matrix:
      - '2.3'
      - '2.4'
      - '2.5'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ["features/rails_features/", "--tags", "@rails3 and not @wip"]
    env:
      RUBY_TEST_VERSION: "{{matrix}}"
      RAILS_VERSION: "3"
    concurrency: 8
    concurrency_group: 'ruby/slow-maze-runner-tests'

  - label: ':rails: Rails 4 Ruby 2.2 tests'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ["features/rails_features/", "--tags", "@rails4 and not @wip"]
    env:
      RUBY_TEST_VERSION: "2.2"
      RAILS_VERSION: "4"
      BUNDLE_VERSION: "1.12.0"
    concurrency: 8
    concurrency_group: 'ruby/slow-maze-runner-tests'

  - label: ':rails: Rails 4 Ruby 2.3 tests'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ["features/rails_features/", "--tags", "@rails4 and not @wip"]
    env:
      RUBY_TEST_VERSION: "2.3"
      RAILS_VERSION: "4"
    concurrency: 8
    concurrency_group: 'ruby/slow-maze-runner-tests'

  - label: ':rails: Rails 5 Ruby {{matrix}} tests'
    matrix:
      - '2.2'
      - '2.3'
      - '2.4'
      - '2.5'
      - '2.6'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ["features/rails_features/", "--tags", "@rails5 and not @wip"]
    env:
      RUBY_TEST_VERSION: "{{matrix}}"
      RAILS_VERSION: "5"
    concurrency: 8
    concurrency_group: 'ruby/slow-maze-runner-tests'

  - label: ':rails: Rails 6 Ruby {{matrix}} tests'
    matrix:
      - '2.5'
      - '2.6'
      - '3.0'
      - '3.1'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ["features/rails_features/", "--tags", "@rails6 and not @wip"]
    env:
      RUBY_TEST_VERSION: "{{matrix}}"
      RAILS_VERSION: "6"
    concurrency: 8
    concurrency_group: 'ruby/slow-maze-runner-tests'

  - label: ':rails: Rails 7 Ruby {{matrix}} tests'
    matrix:
      - '3.0'
      - '3.1'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ["features/rails_features/", "--tags", "@rails7 and not @wip"]
    env:
      RUBY_TEST_VERSION: "{{matrix}}"
      RAILS_VERSION: "7"

  - label: ':rails: Rails integrations Ruby 3.0 tests'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ["features/rails_features/", "--tags", "@rails_integrations"]
    env:
      RUBY_TEST_VERSION: "3.0"
      RAILS_VERSION: "_integrations"
    concurrency: 8
    concurrency_group: 'ruby/slow-maze-runner-tests'

  - label: ':clipboard: Rake Ruby {{matrix}} tests'
    matrix:
      - '1.9.3'
      - '2.0'
      - '2.1'
      - '2.2'
      - '2.3'
      - '2.4'
      - '2.5'
      - '2.6'
      - '2.7'
      - '3.0'
      - '3.1'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ['features/rake.feature', '--tags', 'not @wip']
    env:
      RUBY_TEST_VERSION: "{{matrix}}"
    concurrency: 4
    concurrency_group: 'ruby/integrations-maze-runner-tests'

  - label: ':postbox: Mailman Ruby {{matrix}} tests'
    matrix:
      - '2.0'
      - '2.1'
      - '2.2'
      - '2.3'
      - '2.4'
      - '2.5'
      - '2.6'
      - '2.7'
      - '3.0'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ['features/mailman.feature', '--tags', 'not @wip']
    env:
      RUBY_TEST_VERSION: "{{matrix}}"
    concurrency: 4
    concurrency_group: 'ruby/integrations-maze-runner-tests'

  - label: ':key: Que 0.14 Ruby {{matrix}} tests'
    matrix:
      - '2.0'
      - '2.1'
      - '2.2'
      - '2.3'
      - '2.4'
      - '2.5'
      - '2.6'
      - '2.7'
      - '3.0'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ['features/que.feature', '--tags', 'not @wip']
    env:
      RUBY_TEST_VERSION: '{{matrix}}'
      QUE_VERSION: '0.14'
    concurrency: 4
    concurrency_group: 'ruby/integrations-maze-runner-tests'

  - label: ':key: Que 1.x Ruby {{matrix}} tests'
    matrix:
      - '2.5'
      - '2.6'
      - '2.7'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ['features/que.feature', '--tags', 'not @wip']
    env:
      RUBY_TEST_VERSION: '{{matrix}}'
      QUE_VERSION: '1'
    concurrency: 4
    concurrency_group: 'ruby/integrations-maze-runner-tests'

  - label: ':bed: Rack 1 Ruby {{matrix}} tests'
    matrix:
      - '1.9.3'
      - '2.0'
      - '2.1'
      - '2.2'
      - '2.3'
      - '2.4'
      - '2.5'
      - '2.6'
      - '2.7'
      - '3.0'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ['features/rack.feature', '--tags', 'not @wip']
    env:
      RUBY_TEST_VERSION: '{{matrix}}'
      RACK_VERSION: '1'
    concurrency: 4
    concurrency_group: 'ruby/integrations-maze-runner-tests'

  - label: ':bed: Rack 2 Ruby {{matrix}} tests'
    matrix:
      - '2.2'
      - '2.3'
      - '2.4'
      - '2.5'
      - '2.6'
      - '2.7'
      - '3.0'
      - '3.1'
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.1.0:
        run: ruby-maze-runner
        use-aliases: true
        command: ['features/rack.feature', '--tags', 'not @wip']
    env:
      RUBY_TEST_VERSION: '{{matrix}}'
      RACK_VERSION: '2'
    concurrency: 4
    concurrency_group: 'ruby/integrations-maze-runner-tests'
