steps:
  - group: ":ruby: Unit tests"
    steps:
      - label: ':ruby: JRuby unit tests'
        timeout_in_minutes: 30
        plugins:
          docker-compose#v3.1.0:
            run: jruby-unit-tests
            use-aliases: true
        concurrency: 4
        concurrency_group: 'ruby/unit-tests'

      - label: ':ruby: Ruby {{matrix}} unit tests'
        matrix:
          - '2.0'
          - '2.1'
        timeout_in_minutes: 30
        plugins:
          docker-compose#v3.1.0:
            run: ruby-unit-tests
            use-aliases: true
        env:
          RUBY_TEST_VERSION: "{{matrix}}"
          BUNDLE_VERSION: "1.12.0"
        concurrency: 4
        concurrency_group: 'ruby/unit-tests'

      - label: ':ruby: Ruby {{matrix}} unit tests'
        matrix:
          - '2.2'
          - '2.3'
        timeout_in_minutes: 30
        plugins:
          docker-compose#v3.1.0:
            run: ruby-unit-tests
            use-aliases: true
        env:
          RUBY_TEST_VERSION: "{{matrix}}"
          BUNDLE_VERSION: "1.12.0"
          GEMSETS: "test sidekiq"
        concurrency: 4
        concurrency_group: 'ruby/unit-tests'

      - label: ':ruby: Ruby {{matrix}} unit tests'
        matrix:
          - '2.4'
          - '2.5'
          - '2.6'
        timeout_in_minutes: 30
        plugins:
          docker-compose#v3.1.0:
            run: ruby-unit-tests
            use-aliases: true
        env:
          RUBY_TEST_VERSION: "{{matrix}}"
          GEMSETS: "test sidekiq"
        concurrency: 4
        concurrency_group: 'ruby/unit-tests'

      - label: ':ruby: Ruby {{matrix}} unit tests'
        matrix:
          - '3.0'
          - '3.1'
        timeout_in_minutes: 30
        plugins:
          docker-compose#v3.1.0:
            run: ruby-unit-tests
            use-aliases: true
        env:
          RUBY_TEST_VERSION: "{{matrix}}"
        concurrency: 4
        concurrency_group: 'ruby/unit-tests'
